#:include Screens/auth_background.kv
#:include Screens/login.kv
#:include Screens/register.kv
#:include Screens/profile_setup.kv
#:include Screens/reset_password.kv
#:include Screens/dashboard.kv

ScreenManager:
    id: screen_manager
    LoginScreen:
        name: 'login'
    RegisterScreen:
        name: 'register'
    ProfileSetupScreen:
        name: 'profile_setup'
    PasswordResetScreen:
        name: 'reset_password'
    DashboardScreen:
        name: 'dashboard'
    SendMoneyScreen:
        name: 'send_money'